-- Remove any connects, \c <database_name>, in the file/s that your trying to run against the database. Heroku creates a database with a random name when you add the postgresql database add-on. Therefore, having any connects will cause an error to occur because your connects will be pointing to your local database’s name.

\c kittypawlitics

-- remove any records and start the id sequence back to 1
DROP TABLE IF EXISTS affiliation CASCADE;
DROP TABLE IF EXISTS cats CASCADE;

-- create tables here
CREATE TABLE affiliation (
  id SERIAL PRIMARY KEY,
  name TEXT
);

CREATE TABLE cats (
  id SERIAL PRIMARY KEY,
  name TEXT,
  img_url TEXT,
  blurb TEXT,
  hashtags TEXT,
  issue TEXT,
  backgroundimg_url TEXT,
  affiliation_id INTEGER REFERENCES affiliation(id)
);

-- create affiliation
INSERT INTO affiliation (
 name
 )
VALUES
('Registered Democat'),
('Registered Republicat'),
('Libpurrtarian'),
('Independent');


-- create cats
INSERT INTO cats (
name,
img_url,
blurb,
hashtags,
issue,
backgroundimg_url,
affiliation_id
)
VALUES
('The Siamese Twins', '/siamese.jpg', 'These siblings are well versed in hiss-tory and know that walls have 2 sides and neither side is free! “Tear down that idea of a wall!” They say.', '#dccats #nobannowall #dccitycats #dcfakemews #dccats #siamesecats','Immigration', 'https://images.unsplash.com/photo-1516900548636-f96ad652758e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f823fb60ede8572475e51a2bdf94defc&auto=format&fit=crop&w=634&q=80', 2),
('Savannah', '/savannah.jpg', 'Savannah is an independent lady who needs no man to make her feel purrty. She’s tired of being cat-called when she’s living her life and wants all the girls out there to know', '#metoo. #meowtoo #catsagainstcatcalls #dccats #dcfakemews','Lady Cat Rights', 'https://images.unsplash.com/photo-1513538318453-d0cc70acc86d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f6a18afb60eaea7ba2fdcccea5d0edc6&auto=format&fit=crop&w=400&q=60', 1),
('Coach', '/random.jpg', 'Coach has been a DC kitty and political junky his whole life, but lately the news has been too much for him. “I’d honestly rather just plop down in front of The Office reruns and nibble on some Greenies,” he states with a sigh.', '#dcfakemews #theoffice #netflixandchill #dccats #dccitycats #dcliving', 'Education', 'https://images.unsplash.com/photo-1446761935768-6a5fce86dda5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=06d1360759fe4b26e037d764e47ad36e&auto=format&fit=crop&w=1050&q=80', 1),
('Doris', '/doris.jpg', 'Meet Doris. Although she hates pretty much everyone and everything, what really grinds her gears is hearing that our oceans’ ecosystems are being destroyed by commercial fishing and pollution. “Such a cat-astrophy,” she cries. She also says “Go Pats!”', '#dcfakemews #dccats #protectourreefs #fish #cats #superbowl2018', 'Global Warming', 'https://images.unsplash.com/photo-1530433331547-e064ffe8eef1?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=edf5f2452d2af36fced83fcf02596f03&auto=format&fit=crop&w=400&q=60', 1),
('Willow', '/willow.jpg', 'Willow knows what she does with her body is her choice. “Just because I choose to lay on my back with my legs wide open doesn’t mean you can rub my belly. Lay your paws on me without my consent and you might get a clawed.”', '#sorrynotsorry #mybodymychoice #dcfakemews #independentcats #dccats #metoo #meowtoo #feminism #feministcats', 'Lady Cat Rights', 'https://images.unsplash.com/photo-1499187817214-70f75289a676?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=b63a505fb192eb07a2e7548e4b95b81a&auto=format&fit=crop&w=400&q=60', 1),
('Sonic', '/sonic.jpg', 'Sonic is not your average cisgender cat. They don’t identify by their birth sex and prefers to remain gender-neutral. Their biggest fear is that, while we began to progress during Obama, that the current administration will continue to attack rights of those who have transitioned or those who just don’t identify by standard gender norms. “No matter which litter box I enter, cats look at me like a purrvert,” Sonic says with a tear. Let’s reverse these ideas of gender and promote progressive policies!','#reversegendernorms #allcatscreatedequal #humanrights #dccats #dcfakemews #dclife #chicagocatstoo','LGBTQ Rights', 'https://images.unsplash.com/photo-1513538318453-d0cc70acc86d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f6a18afb60eaea7ba2fdcccea5d0edc6&auto=format&fit=crop&w=400&q=60', 1),
('Luna', '/luna.jpg', 'Luna has recently acknowledged her white privilege. This pretty kitty is ready to have a seat at the table in the conversation about intersectional femeownism. She purrs: “While I’m not trying to discredit Lena Dunham or any other white feminists, the only actual hardships they’ve had to face have to do with the fact that they’re female. There are so many other barriers to equality in America!”', '#intersectionality #feminism #equality #dccats #dcitycats #dcfakemews #lawsoffmypaws #progressive #dc #siamese', 'Social Justice', 'https://images.unsplash.com/photo-1488217820102-3ef7cfe8bb4e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=a6d9552e6b74406a458bcf65b14222b0&auto=format&fit=crop&w=400&q=60', 1),
('Telulah', 'telulah.jpg', 'Miss Telulah is saying “smell ya later” to the swamp. After years working on the hill, she is over it. “Remember when everyone said they were meowving to Canada if a certain someone won? I’m thinking now is the purrfect time,” she says. “Packed my greenies, catnip, and am ready to cross the border to catch mice in greener pastures.” Tell Trudeau we say hello!', '#canada #usa #greenies #catnip #packedherbags #draintheswaml #dccats #dcfakemews #byebye', 'Drain the Swamp', 'https://images.unsplash.com/photo-1487730202306-21b1a371bab0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1f58b23d5fefef6aa469eed5406a745e&auto=format&fit=crop&w=400&q=60', 2),
('Spike', '/spike.jpg', 'Meowchelle Obama inspired Spike to become a healthy cat. He began his journey several years ago, and has since lost 4 lbs!! Currently weighing in at 21 lbs, he’s concerned about healthcare and the rising costs of medication to manage his health conditions! He doesn’t talk much so we could get a quote, but you can see the concern in his eyes.', '#michelleobama #healthcare #dcfakemews #bigcats #meowdication #biggestloser #chicagocats','Healthcare', 'https://images.unsplash.com/photo-1499187817214-70f75289a676?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=b63a505fb192eb07a2e7548e4b95b81a&auto=format&fit=crop&w=400&q=60', 2),
('Anonymous', '/anonymous.jpg', 'Why is our little friend covering their face? “I’m a kittengarden teacher who uses my own money to buy school supplies! The current administration took away the $250 teacher subsidy I rely on to offer our kittens a well rounded eduCATion!” Instead, billionaires get 2 million dollars in inheritance tax deductions. BECAUSE THAT MAKES SENSE!', '#teachers #taxbreaks #dccats #dcfakemews #dccitycats #teachersareourfuture','EducAtion', 'https://images.unsplash.com/photo-1446761935768-6a5fce86dda5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=06d1360759fe4b26e037d764e47ad36e&auto=format&fit=crop&w=1050&q=80', 1),
('Millenial Kitty', '/millenial.jpg', 'Spotted in wild Florida - a lone progressive millennial cat creeping in the nighttime. “Life here is hard,” she squeaks, “but I just love Disney so much. I have a college debt, make minimum wage, don’t have any health benefits and talk to neo-nazis all day, but at least I get to see Mickey whenever I want! I love mice...” ', '#millennials #millennialcats #thisisreal #disneyworld #dcfakemews #creep #florida #floridacats', 'Healtcare', 'https://images.unsplash.com/photo-1530433331547-e064ffe8eef1?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=edf5f2452d2af36fced83fcf02596f03&auto=format&fit=crop&w=400&q=60', 1),
('Jacob & Pema', 'jacob&pema.jpg', 'Jacob and Pema were born on the streets to feral parents. They feel lucky to have found affordable housing in Washington DC, as many other homeless cats do not fare as well. “Having a roof over your head makes it possible to accommodate basic needs, so that we can function as normal cats in society,” Pema says as she cleans herself. “Being able to lick myself clean before interviews, prepare healthy kibble, and sleep in a warm cat tree makes all the difference when I’m searching for jobs,” Jacob chimes in.', '#affordablehousing #homelessness #dccats #jobsearch #healthymeals #dcfakemews #dccitycats', 'Poverty', 'https://images.unsplash.com/photo-1446761935768-6a5fce86dda5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=06d1360759fe4b26e037d764e47ad36e&auto=format&fit=crop&w=1050&q=80', 1),
('Kentucky Kitty', '/kentucky.jpg', 'This just in from a Kentucky kitty - “F*** YOU MITCH MCCONNELL, YOU LYING BASTARD!” He wants the world to know that not all Southern cats are red state pussies!', '#kentucky #mitchmcconnell #liar #DREAMER #dccats #catsofinstagram #dcfakemews', 'Immigration', 'https://images.unsplash.com/photo-1499187817214-70f75289a676?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=b63a505fb192eb07a2e7548e4b95b81a&auto=format&fit=crop&w=400&q=60', 1),
('Scrum, Perl & Bash','/scrum.jpg','Meet Scrum, Perl and Bash. Scrum wants everyone to know that “men can be femeownists too!” Perl starts by saying that they want to congratulate the pawesome Tabby Duckworth and her baby on being femeownist trailblazers on the Senate floor! So much hope there! Butttt, these guys also want to talk about something more serious...Many women, black women specifically, aren’t able to have the same safe access to healthcare during their pregnancies as @senduckworth had with hers. Bash purrs: “Not only is there a lack of hisspital access for many black women, but there are proven studies that being black in Ameowica puts undue stress on those humans, increasing mortality at childbirth. It’s apawling! The Mew York Times also released an article calling out the racism that meownorities experience in medical environments. We knead to TRUST BLACK WOMEN and help them have successful and happy births.” That is deep and vvvv true.', '#trustwomen #trustblackwomen #accesstohealthcare #healthcare #reduceinfantmortality #dccats #dcfakemews #realnews #realfacts #facts #dccats #tripplets #citykitties #scrum #catsofinstagram #cats_of_instagram #cats', 'Social Justice', 'https://images.unsplash.com/photo-1523073477224-0f7a635262c4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=70e68f7819c6ca61641fa2e344060fd2&auto=format&fit=crop&w=400&q=60', 1),
('Bianca & Violet', '/bianca&violet.jpg','Meet Bianca and Violet - two middle-aged felines who have always identified as Republicats. Until 2016. “It’s a gosh darn cat-astrophy,” Bianca says as she curls into a ball. “What happened to family values and living life by the Bible? There ain’t a godly man in the White House if you crawled under the sofas or on top of the refrigerators. The nationalists done cleaned them all out,” Violet meows along. Can’t say I’ve looked in all those places, but I’m tempted to agree!', '#catsofinstagram #sistercats #dcfakemews #dccats #dclife #washingtondc', 'Family Values', 'https://images.unsplash.com/photo-1513538318453-d0cc70acc86d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f6a18afb60eaea7ba2fdcccea5d0edc6&auto=format&fit=crop&w=400&q=60', 2),
('Oscar', '/oscar.jpg','As a feline who depends on Xanax, Oscar knows the importance of medication in his day to day life. “I’m way nicer to strangers and I no longer rage poop outside of my litter box,” he chirps happily. But he’s seen the rate of addiction to opioids in his city increase, by first, carelessly written prescriptions and then, the ease of access to street versions of prescription meds. “One thing leads to another, and your drugs are no longer safe,” he adds. There is an opioid crisis in this country that and our administration isn’t doing enough. We need', '#mentalhealthcare and #safeneedleexchanges. #dcfakemews #dccats #catsofinstagram #opiodcrisis','Mewontal Health', 'https://images.unsplash.com/photo-1488217820102-3ef7cfe8bb4e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=a6d9552e6b74406a458bcf65b14222b0&auto=format&fit=crop&w=400&q=60', 1),
('Miles', 'miles.jpg','This is Miles. He’s confused. “Why are we acting like everything is cool when we know that Russian Meowfia has hacked our social media and meddled in our elections?! I’m not one for cat-spiracy theories, but the evidence against them is mwuuuge”','#mueller #russia #meddling #hacked #dxcitycats #catsofinstagram #dccats #dcfakemews','Global Warming', 'https://images.unsplash.com/photo-1487730202306-21b1a371bab0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1f58b23d5fefef6aa469eed5406a745e&auto=format&fit=crop&w=400&q=60', 1),
('Layla', '/layla.jpg','“There’s nothing more pawesome than watching a sunrise over a lake or a sunset on top of a meowntain,” Layla begins as she sits atop her Smokey Mountain National Park blanket. “National Parks are bigger than you Mr. Trump! There’s nothing more American than the land that existed before we did.” It’s true, Layla! The National Parks Service protects public lands and allows them to be clean, safe and accessible to those who want to appreciate the real America!', '#nationalparks #nps #nationalparkservice #dcfakemews #dccats #dccitycats #mountains #smokeymountains #catsofinstagram #washingtondc #dc #districtofcolumbia', 'Global Warming', 'https://images.unsplash.com/photo-1435097791017-d2a958c96f81?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=523f1f1bc1935552c648fcabedd476a1&auto=format&fit=crop&w=400&q=60', 1),
('Advocate for the middle class', '/middleclass.jpg','While we’ve been primarily focusing on upper-middle class kitties, let’s not forget about our hourly wage workers! This little guy works tirelessly to catch mice in the DMV area. “Hourly mouse fetchers kneed to be making more than the meownimum wage! $7.25 a hour in Virginia is an absolute disgrace. All day people come into the shop, pat my head like I’m some sort of dog, and compliment my looks. Well you know what, compliments don’t pay the bills!” So true, so true.', '#minimumwage #dccats #catsofinstagram #dcfakemews #beer #cats #beercats #raiseminimumwage #virginia #dccitycats #meow','Poverty', 'https://images.unsplash.com/photo-1499187817214-70f75289a676?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=b63a505fb192eb07a2e7548e4b95b81a&auto=format&fit=crop&w=400&q=60', 1),
('Gazpacho', '/gazpacho.jpg','Gazpacho is an indoor princess, but she wishes she could have been advocating for gun control outside the White House today. You can tell by the look in her eyes that common sense gun safety measures are SO important to her. “Those high school kids are doing more to promote the importance of gun control than any Democats or Republicats,” she meows.', '#toomanyguns #gunsafety #guncontrol #dccats #catsofinstagram #dcfakemews #realnews #gazpacho #cats #everytown #demandaction', 'Gun Control', 'https://images.unsplash.com/photo-1530433331547-e064ffe8eef1?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=edf5f2452d2af36fced83fcf02596f03&auto=format&fit=crop&w=400&q=60', 1),
('Preston', '/preston.jpg','This just in from Preston, in Michigan: “I know the Olympics Committee is just a bunch of colonizing assholes and we’re supposed to hate the Russians, but damn was that Ladies Figure skating fight exciting tonight!”', '#olympics #colonizers #wintergames #russia #figureskating #dccats #catsofinstagram #michigan #dcfakemews #realnews #sports #cats','Immigration', 'https://images.unsplash.com/photo-1513538318453-d0cc70acc86d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f6a18afb60eaea7ba2fdcccea5d0edc6&auto=format&fit=crop&w=400&q=60', 1),
('Anonymous Homeless Kitty', '/homeless.jpg','This fluffy bundle of love has been homeless for the last three months and it doesn’t seem to get better. “My whole life I’ve been a factory worker in a biscuit making factory. Three meownths ago, I got injured, when my colleague tipped a glass of water on top of me. I lost my job cuz I could no longer do the physical labor, and got evicted because I couldn’t pay rent. Since then, I’ve been begging for snacks outside of local neighborhood homes. My health care bills are piling up and my debt keeps growing. Being poor is so expensive.” Poor baby!','#cats #catsofinstagram #evicted #kitty #dc #dcfakemews #poor #beingpoorsucks #fluffy #factory','Poverty', 'https://images.unsplash.com/photo-1487730202306-21b1a371bab0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1f58b23d5fefef6aa469eed5406a745e&auto=format&fit=crop&w=400&q=60', 1),
('Mason', '/mason.jpg','Meet Mason! This sentimental Sphynx dreams of a purrgressive world where we all abide by the principals of “One Love” and “No Hair, Don’t Care.” As a self-identified nudist, he has no time for the toxic world of body shaming and back stabbing haunting our nation. “Strip away your insecurities! Strip away your fur coats! What’s inside is beautiful,” he cries', '#nude #sphynxcat #dcfakemews #nudist #nohairdontcare #cats #catsofinstagram #nomorebodyshaming #loveyourself #onelove #dccats #lovecats', 'Purrsitive Body Image', 'https://images.unsplash.com/photo-1487730202306-21b1a371bab0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1f58b23d5fefef6aa469eed5406a745e&auto=format&fit=crop&w=400&q=60', 1),
('Virginia', '/virginia.jpg','This little dixie kitty hails from the south and she’s got a lot of baggage to unpack. Virginia was always taught that the confederate flag and its affiliated statues were hiss-torical relics that should be praised. “It’s part of our past, they would tell me,” she begins. “But the Catfederacy is a shameful time in Americat history! Why should we be saluting racists and bigots?! Wake up and smell the tuna, y’all,” she finishes.', '#cats #dccats #catsofinstagram #confederateflag #catfederacy #takedownthestatues #america #american #americat #history #hisstory #progress', 'Social Justice', 'https://images.unsplash.com/photo-1519373069499-b54fc6ab1802?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f61e540c4eb0f57542bcfa1e8305acde&auto=format&fit=crop&w=400&q=60', 1),
('Betsy', '/betsy.jpg', 'Betsy may be small but her words are strong and pawerful. She is a strong proponent of federal catnip legalization and is sick and tired of catddicts getting treated like criminals. “It’s a mewntal health issue just like all the messed up stuff in this country. Cats are told ‘hide your feelings’ and ‘don’t use your claws.’ We don’t know how to handle our emotions so we self-medicate and the stuff out their ain’t safe!”','#regulateit #catnip #federalregulation #dccats #catsofinstagram #dccitycats #medication #mentalhealth #cats #kitty #betsy', 'Meowntal Health', 'https://images.unsplash.com/photo-1499187817214-70f75289a676?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=b63a505fb192eb07a2e7548e4b95b81a&auto=format&fit=crop&w=400&q=60', 1),
('Tallulah', '/tallulah.jpg','Tallulah is a funky feline who wants to remind everyone that, whenever you feel lost, meowsic is medicine. “It is the sound of generations of revolution, protest and activism. From Cat Stevens to Pussy Riot, meowsicians have inspired people to fight for their truth.” Can’t argue with that! She also wants to send a shout out to @jamiroquaihq - her favorite band!', '#music #meowsic #musicismedicine #cats #dccats #catsofinstagram #funk #funkmusic #chicagocats #revolution #activism #protest #dcfakemews', 'Music Medicine','https://images.unsplash.com/photo-1513538318453-d0cc70acc86d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f6a18afb60eaea7ba2fdcccea5d0edc6&auto=format&fit=crop&w=400&q=60', 1),
('Dusty','/dusty.jpg','Dusty works hard, pays her own bills and is a boss. She’s sick of being told to purr more and that she is not sweet enough. At work, the terms "catty" and "aggressive" are used to describe her leadership style, while her canine counterparts are praised for having the same traits. “Just because I don’t rub my head up against you and beg for your attention, doesn’t mean I’m doing anything wrong. You try being a cat in a dogs world!” Dusty demands that ladycats be taken more seriously in the workplace and rewarded for their accomplishments and NOT PUT IN A SOCIETAL MOLD!', '#dogsworld #mansworld #catty #dcfakenews #catsofinstagram #ladyboss #boss #bosscat #dccats #equalrights #equalpay #survivor #nashville #dc #america', 'Social Justice', 'https://images.unsplash.com/photo-1435097791017-d2a958c96f81?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=523f1f1bc1935552c648fcabedd476a1&auto=format&fit=crop&w=400&q=60', 1),
('Chuck', '/chuck.jpg','Chuck had always identified as a “nice cat.” “Nice cats finish last,” they’d say, and he believed it. After years of finishing last, Chuck became bitter and started spending all of his time on the r/niceguys reddit. He fed off of the internet trolls. “Why won’t any females mount me??” He would cry into the depths of the internet. Then one day, Chuck had an epiphany. “Why don’t I try LISTENING to the females around me,” he thought to himself. Since then, Chuck has gotten off reddit and into the playing field. He’s got ladies mounting him left and right! Congrats, Chuck', '#reddit #niceguy #nicecat #niceguysfinishlast #chuck #chucky #philly #dccats #catsofinstagram #fatcat #dcfakemews #realnews #windowcat #reddit #redditnicecats #redditniceguys', 'Internet Neutrality', 'https://images.unsplash.com/photo-1499187817214-70f75289a676?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=b63a505fb192eb07a2e7548e4b95b81a&auto=format&fit=crop&w=400&q=60', 4),
('Pico', '/pico.jpg','Pico is a purrfect polydactyl who is an #ASPCA rescue. After living a life where survival was the primary focus, he is happy to have found a meowgnificant home. “I know there’s a lot of stigma surrounding stay at home cats, especially males, but protecting the house, hunting mice and making biscuits for my family is my primary responsibility! While my mom is off fighting the patriarchy, this is a full time job!” He also finds time to volunteer at local animal shelters in order to give back to the community.', '#adoptdontshop #aspca #rescue #polydactyl #stayathome #workfromhome #fightthepatriarchy #dccats #catsofinstagram #newyork #newyorkcats #home', 'Equal Rights', 'https://images.unsplash.com/photo-1519373069499-b54fc6ab1802?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f61e540c4eb0f57542bcfa1e8305acde&auto=format&fit=crop&w=400&q=60', 1),
('Lucy', '/lucy2.jpg','The close congressional race in PA 18 has got Lucy fired up! “My pupils are dilated, my tail is in the air, my eyes are on the prize - I’m ready to pounce on those 2018 Primary Ballots, ” she meows. Lucy, like many of us, was angry and disillusioned after the last election. “The stakes are especially high for me, being a lady cat and a feline of color. Females need to unite and vote these Republicat fools out of office. I don’t know if I could ever forgive those pure bred women who voted for Trump, but we have a chance to begin fixing our mistakes.” Furr sure!', '#ladycat #PA18 #vote #gotv #getoutthevote #blacklivesmatter #catsofinstagram #dcfakemews #realnews #dccats #lucy #female #lawsoffmypaws #handsoffmypussy', 'Social Justice', 'https://images.unsplash.com/photo-1499187817214-70f75289a676?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=b63a505fb192eb07a2e7548e4b95b81a&auto=format&fit=crop&w=400&q=60', 1),
('Henry','/henry.jpg','Henry has crawled out of his hole to let us know that he is not feline fine. “When puss comes to shove, we all need to admit that we are living in a real life version of The Apprentice. The “big boss” hires obnoxious catriversial personalities to increase his ratings... and then he fires them or forces them to resign! This time, though, it’s not a joke and he’s not kitten.” This week we said goodbye to Rex, tomorrow we say by to McMaster?? Oy vey!','#yourefired #fired #resigned #tillerson #mcmaster #drama #cats #dcfakemews #dccats #catsofinstagram #holes #ififitsisits #dccitycats #sphynxcat #sphynx #kidding #kitten', 'Social Justice', 'https://images.unsplash.com/photo-1519373069499-b54fc6ab1802?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f61e540c4eb0f57542bcfa1e8305acde&auto=format&fit=crop&w=400&q=60', 1),
('Jenkins', '/jenkins.jpg', 'Hello to Jenkins from Montana! This mountain cat has a few simple pleasures in life - one of them is hunting. “Although I use my claws, paws and teeth to hunt and kill my prey, I understand when some human hunters get defensive about wanting to keep their guns. My sympathy stops with people that say that bump stocks or large assault weapons are on the same playing field as standard rifles. Can you say FAKE MEWS? Some weapons are designed to kill large amounts of people at once, and that’s not cool. Ameowrica shouldn’t be a combat zone!” Gun control and mental health should be at the top of our priority list, little Jenks! ','#mouser #hunter #banassaultweapons #guncontrol #montanacat #cats #hunter #jenkins #dccats #dccitycats #dcfakemews #montana #mountaincat #gunsafety', 'Gun Control', 'https://images.unsplash.com/photo-1513538318453-d0cc70acc86d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f6a18afb60eaea7ba2fdcccea5d0edc6&auto=format&fit=crop&w=400&q=60', 1),
('Earl Grey', '/earlgrey.jpg','Earl Grey is a posh pussy with a knack for sniffing out bullshit (and treats. He says “most recently, my powerful kitty senses have sniffed out a big stinking litter box that hasn’t been cleaned in way too long. The shitbox I’m talking about is Facebook. Facebook holds our identities in their hands and as far as I’m concerned, they aren’t taking proper precautions to punish past abusers or prevent future mishaps. Like, obviously I’m going to keep using Facebook because I need a litter box.... but COME ON!” Interesting take, Earl Grey... I’ll take it.','#facebook #data #transparency #cybersecurity #politics #socialmedia #dccats #dcfakemews #catsofinstagram #litterbox #smelly #greycat #cats #earlgrey #posh #pussy', 'Internet Neutrality', 'https://images.unsplash.com/photo-1435097791017-d2a958c96f81?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=523f1f1bc1935552c648fcabedd476a1&auto=format&fit=crop&w=400&q=60', 3),
('Norbert', '/norbert.jpg','Norbert is a small business owner with a big heart. This city kitty owns a pizza shop in New York City and gets love from humans of all backgrounds and cultures. “I’ve always embraced catilatism and free trade, but our current administration doesn’t know what they’re talking about! Inclusion of immigrants, movement of goods and services and ability for small businesses to compete is important for a prospurr-ing economy. The only things I’m seeing Trump encourage are monopolies and protectionism!” I think we are all a little confused, Norbert. Tariffs on trade and biggest tax cuts for the largest corporations doesn’t sound like free trade to me!', '#trade #economy #smallbusiness #smallbusinessowner #newyork #citykitty #norbert #orangecat #dccats #newyorkcats #dcfakemews #immigrants #capitalism #catsofdc #catsofinstagram #catsofnewyork #bodegacat #airbnb', 'Small Business', 'https://images.unsplash.com/photo-1435097791017-d2a958c96f81?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=523f1f1bc1935552c648fcabedd476a1&auto=format&fit=crop&w=400&q=60', 2),
('Otto', '/otto.jpg','“Meow-y wowwee what a weekend,” Otto chirps. This little guy feels so hopeful after the March for Our Lives yesterday! He says “I am 8 months old, so that makes me high school age in human years.* Those young people have been through so much, yet they’re still optimistic about the future. It’s inspurring! And a special nod of respect to all the kids who came out from less privileged parts of America! Gun safety is intersectional. If those kids are our future, our future is pawesome.”......*no idea if that’s actually true', '#dcfakemews #dccats #michigancats #gunsafety #enoughisenough #marchforourlives #marchforjustice #otto #ottorocket #blackcat #nojusticenopeace #blacklivesmatter #neveragain #catsofig #catsofinstagram #dccitycats', 'Gun Control','https://images.unsplash.com/photo-1446761935768-6a5fce86dda5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=06d1360759fe4b26e037d764e47ad36e&auto=format&fit=crop&w=1050&q=80', 1),
('Reina', '/reina.jpg','Reina is a regal kitty from the Queen City. When she is not at her day job as an execative at the Bank of Amewica, she follows the Stormy Daniels story like a laser pointer. She curled up in front of the TV on Sunday to watch 60 Minutes over a bowl of Fancy Feast and a stiff glass of warm milk. "As mewsual, I am apawled at the conduct of our Purresident," she sighs. "Even with the pawerful energy behind the #MeowToo mewvement, Dognald Trump somehow remains impurrvious to allegations of sexual misclawnduct,” she rolls here eyes. “What really rattles my cage are the mangy cattorneys getting their paws dirty for this creep," but she was in good spirits this morning after fresh reports that managing Dognald Trumpz legal team continues to be, in her words, "like herding cats."', '#dcfakemews #queencity #charlotte #lawyer #lawcats #dccats #northcarolina #nccats #catsofinstagram #justice #stormydaniels #60minutes #kittensofinstagram #royal #royalty #fancyfeast #milk #metoo #feminism #feminist','Lady Cat Rights', 'https://images.unsplash.com/photo-1492309436847-61fcb5871410?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=d2688bd4dbe13746b382609f7237cbc3&auto=format&fit=crop&w=634&q=80', 1),
('Anonymous Aspurrring Actress', '/hollywood.jpg',
'Spotted on the streets of Los Angeles, a beautiful Siamese! “I’m an aspiring catctress,” she says. “I come from money, but I want fame. Ever since I saw Cat in Breakfast at Tiffany’s, my furrture was clear to me! Soon, I decided that I would be the next Sassy in any remake of Homeward Bound. I was born to be fameows, but let me tell you it comes at a cost! This pussy has been grabbed by countless scoundrels and with very little payback. Little female cats don’t have anyone to stand up for them and it’s hard to rise up in this field without being complicit! You’ve heard about Harvey Weinstein and James Franco, but trust me, they aren’t the only ones! At this point, I’d be willing to settle for Meow Mix commercial. I wasn’t born to be an extra for the rest of my life and I don’t want trade my purride for fame.” Wow, so real little kitty.', '#la #lacats #outsidecats #famouscats #cat #sassy #homewardbound #breakfast #citykitty #DCFakeMews #catsofinstagram #harveyweinstein #jamesfranco', 'Lady Cat Rights', 'https://images.unsplash.com/photo-1513538318453-d0cc70acc86d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f6a18afb60eaea7ba2fdcccea5d0edc6&auto=format&fit=crop&w=400&q=60', 1),
('Twix', '/twix.jpg','Twix wants to talk about meowntal health... and we all should want to talk about it! “From depression to PTSD; From anxiety to OCD; modern society throws a lot of squeaky toys in our direction- these things may appear nice, but they’re annoying as hell. The 9-5, 5 day workweek was created by Type-A kitties, while most cats are meant to sleep all day. Social media and video games furrequently produce enough stimulation and trauma to make any feline dash under the couch. Not only that, but our diets of hormones and chemicals make us feel horrible about ourselves. Shit, I’m named after a candy bar! How can anyone be meowntally healthy in such a sick society?? Take me back to days of napping in the sun and fending for my own mice. I’d trade that for a full time job any day!”', ' #mentalhealth #meowntalhealth #normalizeit #dccats #catsofinstagram #greeneyes #tortoiseshellcat #dccitycats #newyork #nyc #newyorkcats #twix #candy #sunshine #naps #vacation #mice', 'Meowntal Health', 'https://images.unsplash.com/photo-1519373069499-b54fc6ab1802?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f61e540c4eb0f57542bcfa1e8305acde&auto=format&fit=crop&w=1052&q=80', 1),
('Penny Lane', '/pennylane.jpg','Penny Lane is in my ears and in my eyes...about Dognald Trumps treatment of the military! She says “first he wants a military purrade, then he talks about the mewclear button, and now he wants to withdraw troops from Syria and put others on the Meowxican border where they’re not needed! What gives?! I’m all about peace and catflict resolutions, but we’ve got to respect our troops.” It’s true, PL. I too think we spend too much on defense, but recklessness is not good. These are people’s lives we’re talking about!','#pennylane #mexico #syria #military #nuclearbutton #becareful #trump #drumpf #dccats #catsofinstagram #dccitycats #whitecat #nobannowall #dcfakemews #realnews','Peace & Conflict Resolution', 'https://images.unsplash.com/photo-1523073477224-0f7a635262c4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=70e68f7819c6ca61641fa2e344060fd2&auto=format&fit=crop&w=400&q=60', 1),
('Vanna', '/vanna.jpg','She may look like a delicate beauty, but underneath her soft exterior lies a fierce femeownist and abortion advo-cat. Hailing from a small midwestern town where sex-ed meant abstinence, Vanna never learned about safe and effective birth control. “As a one year old kitten, I became pregnant. My parents expected me to get meowied, but I refused, so my parents kicked meowt and I was left on the streets. I was pregnant with six kittens, unable to afford food, let alone abortion! My kittens were born in a box behind a farm. Everyone LOVES kittens, but kittens grow up to be cats. And poor cats whose parents can’t afford eduCATion and shelter grow up to eat your garbage, and no one likes that. With luck, my babies were soon adopted! It took me another year to find my furrever family, since no one is pro-life for real adult cats, but now I’m happy!” Wow Vanna. I think we know some humans who can relate!','#abortion #proabortion #safeabortions #sexed #dccats #catsofinstagram #whitecats #dcfakemews #chicago #chicagokitty #chicats #kittens #healthcare #progress #adoptdontshop #adopt #vannawhite', 'Lady Cat Rights', 'https://images.unsplash.com/photo-1513538318453-d0cc70acc86d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f6a18afb60eaea7ba2fdcccea5d0edc6&auto=format&fit=crop&w=400&q=60', 1),
('Lucky', '/lucky.jpg','Lucky finds it amewsing and ironic that people think she’s bad luck, but it wasn’t always that way. It took her a long time to be comfurrtable in her shiny dark coat. “Black cats are bad luck, they say. We are treated like second class kittizens. Did you know that black cats are less likely to get adopted than any other cat? And on Halloween black cats are often captured, injured and even killed! This Friday the 13th, please take a moment to appreciate a black kitty near you and give them a little extra love. Treat all cats equally!” Oh Lucky, such wise words!','#dccats #dccitycats #nyccats #blackcatsmatter #blackcatsrule #blackcats #fridaythe13th #friday #friyay #dontdiscriminate #donthate #love #catlove #cats #dcfakemews #goodluck #badluck #lucky', 'Social Justice', 'https://images.unsplash.com/photo-1513538318453-d0cc70acc86d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f6a18afb60eaea7ba2fdcccea5d0edc6&auto=format&fit=crop&w=400&q=60', 1),
('Lucy', '/lucy.jpg','We interviewed Lucy, the newest resident of Yang Market in Eckington. Although bright eyed and bushy tailed, this meowllenial knows the importance of maintaining cultural consistency within the reality of changing dc neighpurrhoods. “I’m a young cat in an old part of town,” she meows as she sips a meowscato. “Being a good neighpurr and serving the commewnity is an important part of my role here at Yang Market. The reality is that DC is changing, but that doesn’t mean we have to turn our tails to those who have lived here forever!” Damn Lucy, I’ll take a Catpri Sun and the Jerry Gallo sandwich.','#yanglife #yangmarketne #yangmarketnedeli #eckington #dc #buylocal #dccats #dcfakemews #dccitycats #catsofinstagram #cats_of_instagram #greycat #lucy #prettykitty #bodegacats #bodegacatsofinstagram #bodegacatsofinstagram', 'Social Justice', 'https://images.unsplash.com/photo-1446761935768-6a5fce86dda5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=06d1360759fe4b26e037d764e47ad36e&auto=format&fit=crop&w=1050&q=80', 1),
('Princess Butterscotch', '/butterscotch.jpg', 'This is Princess Butterscotch. She says “I want my future children to have access to safe and affordable health care!', '#CHIP #dccats #catsofdc #dcfakemews #thepeetapeisreal', 'Education', 'https://images.unsplash.com/photo-1435097791017-d2a958c96f81?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=523f1f1bc1935552c648fcabedd476a1&auto=format&fit=crop&w=400&q=60', 1),
('Leo', '/leo.jpg', 'Leo is a young, gay feline who came out in the last year and wants to join the army when he’s older. “You’ve got to be kitten me,” he says, “anyone that wants to fight for our country should be able to!','#dccats #pawlitics #dcgaycats #USA #dccatsrule #dcfakemews', 'LGBTQ Rights', 'https://images.unsplash.com/photo-1499187817214-70f75289a676?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=b63a505fb192eb07a2e7548e4b95b81a&auto=format&fit=crop&w=400&q=60', 2),
('Kitty', '/kitty.jpg', 'This is Tomas, street name “Kitty,” because he’s ashamed of his immigrant roots. He voted for Donald Trump and now he lives in fear, because his family may be deported. Let’s all help him and his family get back on their feet!', '#dccats #catshame #kitty #catsofdc #bloomingdale #dcfakemews', 'Immigration', 'https://images.unsplash.com/photo-1513538318453-d0cc70acc86d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f6a18afb60eaea7ba2fdcccea5d0edc6&auto=format&fit=crop&w=400&q=60', 1);
